os:
  - linux
  - osx
language: generic # default is ruby
dist: trusty
sudo: required
osx_image: xcode8
env:
  - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-06-20-a
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
cache:
    directories:
      - $HOME/.swiftenv
script:
  - swift build && swift test
